# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('issued_by', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SaveLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='doc.SaveLocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doc',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.SaveLocation'),
        ),
    ]
