# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_collection_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='location',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.SaveLocation', verbose_name='Nơi lưu'),
        ),
    ]
