# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='doc.Project', verbose_name='Dự án'),
        ),
    ]
