# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_auto_20170322_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='date',
            field=models.DateField(verbose_name='Ngày'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='issued_by',
            field=models.CharField(max_length=250, verbose_name='Nơi ban hành'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.SaveLocation', verbose_name='Nơi lưu'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='summary',
            field=models.TextField(verbose_name='Trích yếu'),
        ),
    ]
